/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.DonViTinhDAO;
import dao.HoaDonChiTietDAO;
import dao.HoaDonDAO;
import dao.NhanVienDAO;
import dao.SanPhamDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.DonViTinh;
import model.HoaDon;
import model.HoaDonChiTiet;
import model.NhanVien;
import model.SanPham;

/**
 *
 * @author vvtvo
 */
public class HoaDonChiTietJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonChiTietJFrame
     */
    public HoaDonChiTietJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaHD = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDCC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Danh sách mã hóa đơn");

        tblMaHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã HD", "Ngày tạo", "Tên NV"
            }
        ));
        tblMaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaHD);

        tblHDCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "ĐVT", "SL", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tblHDCC);

        jLabel2.setText("Chi tiết hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaHDMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            String mahd = String.valueOf(tblMaHD.getValueAt(tblMaHD.getSelectedRow(), 0).toString());
            fillTableHDCC(mahd);
        }

    }//GEN-LAST:event_tblMaHDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonChiTietJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonChiTietJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHDCC;
    private javax.swing.JTable tblMaHD;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        fillTableMaHD();
    }
    HoaDonDAO hddao = new HoaDonDAO();
    HoaDonChiTietDAO ccdao = new HoaDonChiTietDAO();
    SanPhamDAO spdao = new SanPhamDAO();
    DonViTinhDAO dtdao = new DonViTinhDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    void fillTableMaHD() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblMaHD.getModel();
            model.setRowCount(0);
            List<HoaDon> list = hddao.selectAll();
            for (HoaDon hd : list) {
                NhanVien nv = nvdao.selectById(hd.getMaNV());
                Object[] row = {
                    hd.getMaHD(), hd.getNgayTao(), nv.getTenNV()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void fillTableHDCC(String mahd) {
        DefaultTableModel model = (DefaultTableModel) tblHDCC.getModel();
        model.setRowCount(0);
        List<HoaDonChiTiet> list = ccdao.selectByHD(mahd);
        for (HoaDonChiTiet cc : list) {
            SanPham sp = spdao.selectById(cc.getMaSP());
            DonViTinh dvt = dtdao.selectById(sp.getMaDVT());
            Object[] row = {
                cc.getMaSP(), sp.getTenSP(), dvt.getTenDVT(), cc.getSoLuong(), cc.getDonGia(), cc.getThanhTien()
            };
            model.addRow(row);
        }
    }
}
